# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_gui.ui'
#
# Created: Wed Apr 17 09:59:43 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(633, 714)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cmb_pulse_name = QtGui.QComboBox(self.widget)
        self.cmb_pulse_name.setEditable(False)
        self.cmb_pulse_name.setObjectName("cmb_pulse_name")
        self.gridLayout.addWidget(self.cmb_pulse_name, 2, 2, 1, 1)
        self.btn_add_param = QtGui.QToolButton(self.widget)
        self.btn_add_param.setObjectName("btn_add_param")
        self.gridLayout.addWidget(self.btn_add_param, 3, 3, 1, 1)
        self.btn_browse_config_file = QtGui.QToolButton(self.widget)
        self.btn_browse_config_file.setObjectName("btn_browse_config_file")
        self.gridLayout.addWidget(self.btn_browse_config_file, 1, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.le_pulprog_file = QtGui.QLineEdit(self.widget)
        self.le_pulprog_file.setObjectName("le_pulprog_file")
        self.gridLayout.addWidget(self.le_pulprog_file, 5, 2, 1, 1)
        self.btn_browse_pulprog_file = QtGui.QToolButton(self.widget)
        self.btn_browse_pulprog_file.setObjectName("btn_browse_pulprog_file")
        self.gridLayout.addWidget(self.btn_browse_pulprog_file, 5, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.le_config_file = QtGui.QLineEdit(self.widget)
        self.le_config_file.setObjectName("le_config_file")
        self.gridLayout.addWidget(self.le_config_file, 1, 2, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rbtn_from_config = QtGui.QRadioButton(self.widget)
        self.rbtn_from_config.setChecked(True)
        self.rbtn_from_config.setObjectName("rbtn_from_config")
        self.horizontalLayout_3.addWidget(self.rbtn_from_config)
        self.line_2 = QtGui.QFrame(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rbtn_from_pulprog = QtGui.QRadioButton(self.widget)
        self.rbtn_from_pulprog.setObjectName("rbtn_from_pulprog")
        self.horizontalLayout_4.addWidget(self.rbtn_from_pulprog)
        self.line_3 = QtGui.QFrame(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_4.addWidget(self.line_3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 7)
        self.btn_del_param = QtGui.QToolButton(self.widget)
        self.btn_del_param.setObjectName("btn_del_param")
        self.gridLayout.addWidget(self.btn_del_param, 3, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 5, 1, 1)
        self.tab_parameters = QtGui.QTableWidget(self.widget)
        self.tab_parameters.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tab_parameters.setObjectName("tab_parameters")
        self.tab_parameters.setColumnCount(2)
        self.tab_parameters.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tab_parameters.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tab_parameters.setHorizontalHeaderItem(1, item)
        self.tab_parameters.horizontalHeader().setStretchLastSection(True)
        self.tab_parameters.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tab_parameters, 3, 2, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_edit_pulprog = QtGui.QPushButton(self.widget)
        self.btn_edit_pulprog.setToolTip("")
        self.btn_edit_pulprog.setObjectName("btn_edit_pulprog")
        self.horizontalLayout_5.addWidget(self.btn_edit_pulprog)
        self.btn_compile_pulprog = QtGui.QPushButton(self.widget)
        self.btn_compile_pulprog.setToolTip("")
        self.btn_compile_pulprog.setObjectName("btn_compile_pulprog")
        self.horizontalLayout_5.addWidget(self.btn_compile_pulprog)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 1, 1, 4)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_7.addWidget(self.line_5)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_view_config = QtGui.QPushButton(self.centralwidget)
        self.btn_view_config.setToolTip("")
        self.btn_view_config.setObjectName("btn_view_config")
        self.horizontalLayout_8.addWidget(self.btn_view_config)
        self.btn_preview = QtGui.QPushButton(self.centralwidget)
        self.btn_preview.setToolTip("")
        self.btn_preview.setObjectName("btn_preview")
        self.horizontalLayout_8.addWidget(self.btn_preview)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_open = QtGui.QPushButton(self.centralwidget)
        self.btn_open.setToolTip("")
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout_2.addWidget(self.btn_open)
        self.btn_close = QtGui.QPushButton(self.centralwidget)
        self.btn_close.setToolTip("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.btn_preconfigure = QtGui.QPushButton(self.centralwidget)
        self.btn_preconfigure.setToolTip("")
        self.btn_preconfigure.setObjectName("btn_preconfigure")
        self.horizontalLayout_2.addWidget(self.btn_preconfigure)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.btn_start = QtGui.QPushButton(self.centralwidget)
        self.btn_start.setToolTip("")
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_2.addWidget(self.btn_start)
        self.btn_stop = QtGui.QPushButton(self.centralwidget)
        self.btn_stop.setToolTip("")
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_2.addWidget(self.btn_stop)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_6.addWidget(self.line_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.te_console = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.te_console.sizePolicy().hasHeightForWidth())
        self.te_console.setSizePolicy(sizePolicy)
        self.te_console.setMaximumSize(QtCore.QSize(16777215, 1000))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.te_console.setFont(font)
        self.te_console.setReadOnly(True)
        self.te_console.setObjectName("te_console")
        self.verticalLayout.addWidget(self.te_console)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "X6-1000M Control Console", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add_param.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_browse_config_file.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Pulse Name", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_browse_pulprog_file.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.rbtn_from_config.setText(QtGui.QApplication.translate("MainWindow", "From Pulse Configuration File", None, QtGui.QApplication.UnicodeUTF8))
        self.rbtn_from_pulprog.setText(QtGui.QApplication.translate("MainWindow", "From Pulse Program", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_del_param.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Override Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Pulse Program", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Pulse Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_parameters.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_parameters.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_edit_pulprog.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_compile_pulprog.setText(QtGui.QApplication.translate("MainWindow", "Compile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Configuration Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_view_config.setText(QtGui.QApplication.translate("MainWindow", "View Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_preview.setText(QtGui.QApplication.translate("MainWindow", "Preview Program", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Device and Stream Control", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_open.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_close.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_preconfigure.setText(QtGui.QApplication.translate("MainWindow", "Preconfigure", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_start.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Console", None, QtGui.QApplication.UnicodeUTF8))

